---

- name: Create src dir
  file: path=/root/src state=directory


- name: Check if cuda-8-0 is installed
  command: dpkg-query -W cuda-8-0
  register: cuda_check_deb
  failed_when: cuda_check_deb.rc > 1
  changed_when: cuda_check_deb.rc == 1

- name: copy repo to remote
  copy:
    src: "{{cuda_repo}}.deb"
    dest: "/root/src/{{cuda_repo}}.deb"
  when: cuda_check_deb.rc == 1

- name: "add nvidia cuda deb"
  apt:
    deb: "/root/src/{{cuda_repo}}.deb"
  when: cuda_check_deb.rc == 1

- name: Update repositories cache and install "cuda-8-0" package
  apt:
    name: cuda-8-0
    update_cache: yes
  when: cuda_check_deb.rc == 1

- unarchive: src="{{cudnn_file}}.tgz" dest=/root/src/ mode=0755 owner=root group=root creates=/root/src/cuda/include/cudnn.h

- copy:
    src: /root/src/cuda/include/cudnn.h
    dest: /usr/local/cuda/include/cudnn.h
    mode: 0644
    remote_src: True

- name: copy libs
  copy:
    src: /root/src/cuda/lib64/{{item}}
    dest: /usr/local/cuda/lib64/
    mode: 0644
    remote_src: True
  with_items:
    ['libcudnn.so', 'libcudnn.so.6', 'libcudnn.so.6.0.21', 'libcudnn_static.a']

- lineinfile:
    dest: /root/.bashrc
    regexp: '^export LD_LIBRARY_PATH='
    line: 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64"'

- lineinfile:
    dest: /root/.bashrc
    regexp: '^export CUDA_HOME='
    line: 'export CUDA_HOME=/usr/local/cuda'
